# Generated by Django 5.0.2 on 2024-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at'], 'verbose_name': 'user post'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', '-joined_at'], 'verbose_name': 'user from the app'},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique username/email'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_blog',
        ),
    ]
