# Generated by Django 5.0.2 on 2024-03-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='json',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='webpage',
        ),
    ]
