# Generated by Django 5.0.2 on 2024-03-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagedetails', '0002_book_author_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books_info',
        ),
    ]
