# Generated by Django 5.0.2 on 2024-03-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagedetails', '0005_author_alter_book_rating_alter_book_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
