# Generated by Django 5.0.2 on 2024-03-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagedetails', '0008_address_author_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='Author Address',
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author Details',
        ),
        migrations.AlterModelTable(
            name='book',
            table='Author Books info',
        ),
    ]
