# Generated by Django 5.0.2 on 2024-03-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storagedetails', '0010_country_book_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries Name'},
        ),
        migrations.AlterModelTable(
            name='country',
            table='Author Published',
        ),
    ]
