# Generated by Django 5.0.2 on 2024-03-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=70)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'Details',
            },
        ),
    ]
