# Generated by Django 5.0.2 on 2024-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdetails',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='booksdetails',
            table='Receiver info',
        ),
    ]
